### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by pkieltyka** [justinfx/openimageigo#2]
Hi Justin,

Thanks for strong-holding this project. I'm happy to see more image processing libraries for Go. Can you add some more in the README what motivates you to write this project? goals? perhaps some early benchmarks for resizing or other uses compared to something like gographics/imagick? 

cheers.
-Peter

**Comment by justinfx** [comment]
Thanks for the complements. I can definitely expand the README to include motivations. It definitely wasn't motivated by speed vs ImageMagick. Moreso about integration in VFX pipelines. OpenImageIO has indepth support for a number of common VFX formats (such as OpenEXR 2.0). Additionally, it has transparent integration with OpenColorIO, which is the framework for a Color Transformation pipelines (applying LUTs).

**Comment by justinfx** [comment]
After thinking about this some more, I wonder... is there a reason to list goals and benchmarks, if this library is purely a binding to a C++ library with its own goals? Would I just be re-listing the goals of OpenImageIO? Or do you mean that it would be beneficial to compare benchmarks of similar tasks between the OpenImageiGO library vs the Imagick library?

**Comment by iwootten** [comment]
@justinfx Does your particular VFX pipeline use a lot of other go libs already?

**Comment by justinfx** [comment]
@iwootten , I wouldn't say that there has been extensive permeation of Go throughout the pipeline, yet. We have a few command line tools in Go, as well as a few services. But there are more projects in the works, and I think it will continue to pick up.
